stages:
  - test
  - sonarcloud

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

test:
  image: node:18
  stage: test
  script:
    - npm ci
    - npm test -- --coverage
  artifacts:
    paths:
      - coverage/lcov.info
    expire_in: 1 hour

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: sonarcloud
  dependencies:
    - test
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop
    - main
